---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sqlpvclaim1
  namespace: production
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
