apiVersion: batch/v1
kind: Job
metadata:
  name: pg-provisioning
  namespace: db-hosts
spec:
  template:
    metadata:
      name: pg-provisioning
    spec:
      containers:
      - name: pg-provisioning
        image: ericskang/db-provisioning-job:pgsql
        command: ["/bin/bash", "-c", "./provisioning.sh"]
      restartPolicy: Never
